# Generated by Django 4.2.7 on 2023-12-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('ModelNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZipCode', models.CharField(max_length=10)),
                ('Timestamp', models.DateTimeField()),
                ('HourlyRate', models.FloatField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('UnitNumber', models.CharField(blank=True, max_length=10)),
                ('MoveInDate', models.DateField()),
                ('SquareFoot', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('Occupants', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledDevice',
            fields=[
                ('DeviceID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.customer')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.servicelocation')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('EventLabel', models.CharField(max_length=255)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.customer')),
                ('DeviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.enrolleddevice')),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shems_app.servicelocation')),
            ],
        ),
    ]
