# Generated by Django 4.2.7 on 2023-12-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0002_devicemodel_energyprice_servicelocation_and_more'),
    ]

    operations = [
    ]
