# Generated by Django 4.2.7 on 2023-12-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0003_auto_20231213_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='EnergyConsumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
