# Generated by Django 4.2.7 on 2023-12-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0004_devicehistory_energyconsumption_and_more'),
    ]

    operations = [
    ]
