# Generated by Django 4.2.7 on 2023-12-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0005_auto_20231213_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='Timestamp',
            field=models.DateTimeField(),
        ),
    ]
