# Generated by Django 4.2.7 on 2023-12-20 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shems_app', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
